apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: anyf61iro-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-896f406fd4.bw7c.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:4f03b67fd69821e0588d1161aa6bc38bbd0c60de@sha256:20d970646521d8fa563a6e0540bd911afbc59050f26185a30da8536ddc3ac2a6
          name: container-image
