apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: anyf61iro-nodejs
  janus-idp.io/tekton: anyf61iro-nodejs
  backstage.io/kubernetes-id: anyf61iro-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: anyf61iro-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
